#include <QtGlobal>
// Automatically generated by extract_strings.py
static const char *bitcoin_strings[] = {QT_TRANSLATE_NOOP("winnercoin-core", "Winnercoin version"),
QT_TRANSLATE_NOOP("winnercoin-core", "Usage:"),
QT_TRANSLATE_NOOP("winnercoin-core", "Send command to -server or bitcoind"),
QT_TRANSLATE_NOOP("winnercoin-core", "List commands"),
QT_TRANSLATE_NOOP("winnercoin-core", "Get help for a command"),
QT_TRANSLATE_NOOP("winnercoin-core", "Options:"),
QT_TRANSLATE_NOOP("winnercoin-core", "Specify configuration file (default: winnercoin.conf)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Specify pid file (default: bitcoind.pid)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Generate coins"),
QT_TRANSLATE_NOOP("winnercoin-core", "Don't generate coins"),
QT_TRANSLATE_NOOP("winnercoin-core", "Start minimized"),
QT_TRANSLATE_NOOP("winnercoin-core", "Specify data directory"),
QT_TRANSLATE_NOOP("winnercoin-core", "Specify connection timeout (in milliseconds)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Connect through socks4 proxy"),
QT_TRANSLATE_NOOP("winnercoin-core", "Allow DNS lookups for addnode and connect"),
QT_TRANSLATE_NOOP("winnercoin-core", "Listen for connections on <port> (default: 21088 or testnet: 18333)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Maintain at most <n> connections to peers (default: 125)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Add a node to connect to"),
QT_TRANSLATE_NOOP("winnercoin-core", "Connect only to the specified node"),
QT_TRANSLATE_NOOP("winnercoin-core", "Don't accept connections from outside"),
QT_TRANSLATE_NOOP("winnercoin-core", "Don't bootstrap list of peers using DNS"),
QT_TRANSLATE_NOOP("winnercoin-core", "Threshold for disconnecting misbehaving peers (default: 100)"),
QT_TRANSLATE_NOOP("winnercoin-core", ""
"Number of seconds to keep misbehaving peers from reconnecting (default: "
"86400)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Maximum per-connection receive buffer, <n>*1000 bytes (default: 10000)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Maximum per-connection send buffer, <n>*1000 bytes (default: 10000)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Don't attempt to use UPnP to map the listening port"),
QT_TRANSLATE_NOOP("winnercoin-core", "Attempt to use UPnP to map the listening port"),
QT_TRANSLATE_NOOP("winnercoin-core", "Fee per kB to add to transactions you send"),
QT_TRANSLATE_NOOP("winnercoin-core", "Accept command line and JSON-RPC commands"),
QT_TRANSLATE_NOOP("winnercoin-core", "Run in the background as a daemon and accept commands"),
QT_TRANSLATE_NOOP("winnercoin-core", "Use the test network"),
QT_TRANSLATE_NOOP("winnercoin-core", "Output extra debugging information"),
QT_TRANSLATE_NOOP("winnercoin-core", "Prepend debug output with timestamp"),
QT_TRANSLATE_NOOP("winnercoin-core", "Send trace/debug info to console instead of debug.log file"),
QT_TRANSLATE_NOOP("winnercoin-core", "Send trace/debug info to debugger"),
QT_TRANSLATE_NOOP("winnercoin-core", "Username for JSON-RPC connections"),
QT_TRANSLATE_NOOP("winnercoin-core", "Password for JSON-RPC connections"),
QT_TRANSLATE_NOOP("winnercoin-core", "Listen for JSON-RPC connections on <port> (default: 11088)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Allow JSON-RPC connections from specified IP address"),
QT_TRANSLATE_NOOP("winnercoin-core", "Send commands to node running on <ip> (default: 127.0.0.1)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Set key pool size to <n> (default: 100)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Rescan the block chain for missing wallet transactions"),
QT_TRANSLATE_NOOP("winnercoin-core", ""
"\n"
"SSL options: (see the Winnercoin Wiki for SSL setup instructions)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Use OpenSSL (https) for JSON-RPC connections"),
QT_TRANSLATE_NOOP("winnercoin-core", "Server certificate file (default: server.cert)"),
QT_TRANSLATE_NOOP("winnercoin-core", "Server private key (default: server.pem)"),
QT_TRANSLATE_NOOP("winnercoin-core", ""
"Acceptable ciphers (default: TLSv1+HIGH:!SSLv2:!aNULL:!eNULL:!AH:!3DES:"
"@STRENGTH)"),
QT_TRANSLATE_NOOP("winnercoin-core", "This help message"),
QT_TRANSLATE_NOOP("winnercoin-core", ""
"Cannot obtain a lock on data directory %s.  Winnercoin is probably already "
"running."),
QT_TRANSLATE_NOOP("winnercoin-core", "Loading addresses..."),
QT_TRANSLATE_NOOP("winnercoin-core", "Error loading addr.dat"),
QT_TRANSLATE_NOOP("winnercoin-core", "Loading block index..."),
QT_TRANSLATE_NOOP("winnercoin-core", "Error loading blkindex.dat"),
QT_TRANSLATE_NOOP("winnercoin-core", "Loading wallet..."),
QT_TRANSLATE_NOOP("winnercoin-core", "Error loading wallet.dat: Wallet corrupted"),
QT_TRANSLATE_NOOP("winnercoin-core", "Error loading wallet.dat: Wallet requires newer version of Winnercoin"),
QT_TRANSLATE_NOOP("winnercoin-core", "Wallet needed to be rewritten: restart Winnercoin to complete"),
QT_TRANSLATE_NOOP("winnercoin-core", "Error loading wallet.dat"),
QT_TRANSLATE_NOOP("winnercoin-core", "Rescanning..."),
QT_TRANSLATE_NOOP("winnercoin-core", "Done loading"),
QT_TRANSLATE_NOOP("winnercoin-core", "Invalid -proxy address"),
QT_TRANSLATE_NOOP("winnercoin-core", "Invalid amount for -paytxfee=<amount>"),
QT_TRANSLATE_NOOP("winnercoin-core", ""
"Warning: -paytxfee is set very high.  This is the transaction fee you will "
"pay if you send a transaction."),
QT_TRANSLATE_NOOP("winnercoin-core", "Error: CreateThread(StartNode) failed"),
QT_TRANSLATE_NOOP("winnercoin-core", "Warning: Disk space is low  "),
QT_TRANSLATE_NOOP("winnercoin-core", ""
"Unable to bind to port %d on this computer.  Winnercoin is probably already "
"running."),
QT_TRANSLATE_NOOP("winnercoin-core", ""
"Warning: Please check that your computer's date and time are correct.  If "
"your clock is wrong Winnercoin will not work properly."),
QT_TRANSLATE_NOOP("winnercoin-core", "beta"),
};
